name: Share Job Data
on: push
jobs:
    before:
        runs-on: ubuntu-latest
        steps:
            - id: generate
              run: echo "result=Hello" >> "${GITHUB_OUTPUT}"
        outputs:
            result: ${{ steps.generate.outputs.result }}
    after:
        needs: [before]
        runs-on: ubuntu-latest
        steps:
            - run: echo "${RESULT}"
              env:
                RESULT: ${{ needs.before.outputs.result }}
